#include "..\include\article.h"
/**
 * @brief Construct a new Article:: Article object
 * 
 * @param id_param 
 * @param category_param 
 * @param name_param 
 * @param number_sold_param 
 * @param revenue_param 
 */
Article::Article(int id_param , string category_param , string name_param , int number_sold_param , int revenue_param ){
    id = id_param;
    category = category_param;
    name = name_param; 
    number_sold =number_sold_param;
    article_revenue = revenue_param;
}
/**
 * @brief Destroy the Article:: Article object
 * 
 */
Article::~Article(){
    //nothing
}
/**
 * @brief Get the article id object
 * 
 * @return int 
 */
int Article:: get_article_id(){
    return id;
}
/**
 * @brief Get article name 
 * 
 * @return string 
 */
string Article::get_article_name(){
    return name;
}
/**
 * @brief Get article category
 * 
 * @return string 
 */
string Article::get_category(){
    return category;
}
/**
 * @brief Get number of article sold 
 * 
 * @return int 
 */
int Article::get_num_article_sold(){
     return number_sold;
}
/**
 * @brief Get revenue generated by that article
 * 
 * @return int 
 */
int Article::get_revenue(){
     return article_revenue;
}
