#include "../include/shopStatistics.h"
/*
here is  a test program that initaites the data in to the vector, 

and then shuffles or sorts the it arcodding to amount of revenue generated by each shop which is one of the functionalities to be provided by this module.

*/
int main(){
    cout << endl;
    cout << "here is  a test program" << endl;
    ShopStatistic example1;
    example1.instantiate_data();
    example1.sorting_listOfShops_in_order_of_highest_income();
    example1.print_sytsem();
    return 0;
}